apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: ssg-license
    namespace: sgw-ephemeral
    files:
    - ../secret-refs/Enable_U_5463001580886351669_SSG_Enterprise_11.xml
    type: Opaque
  - name: ssg-secret
    namespace: sgw-ephemeral
    envs:
      - ssg-secret.env
    
